---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
    customize:
      cpus: 2
      memory: 1024
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
    - recipe[jolicode-php::default]
    - recipe[jolicode-php::composer]
    - recipe[jolicode-php::ext-apc]
    - recipe[jolicode-php::ext-curl]
    - recipe[jolicode-php::ext-dom]
    - recipe[jolicode-php::ext-fpm]
    - recipe[jolicode-php::ext-gd]
    - recipe[jolicode-php::ext-imagick]
    - recipe[jolicode-php::ext-intl]
    - recipe[jolicode-php::ext-mbstring]
    - recipe[jolicode-php::ext-mcrypt]
    - recipe[jolicode-php::ext-mysql]
    - recipe[jolicode-php::ext-pdo]
    - recipe[jolicode-php::ext-posix]
    - recipe[jolicode-php::ext-twig]
    - recipe[jolicode-php::ext-xdebug]
    - recipe[minitest-handler]